# Generated by Django 3.0.5 on 2021-03-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='interested_investors',
            field=models.ManyToManyField(blank=True, related_name='interested_investors', to='login.Investor'),
        ),
    ]
