# Generated by Django 3.0.5 on 2021-03-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='int_startups',
            field=models.ManyToManyField(to='login.Startup'),
        ),
    ]
