# Generated by Django 3.0.5 on 2021-03-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_investor_int_startups'),
        ('login', '0003_startup_interested_investors'),
    ]

    operations = [
    ]
