# Generated by Django 3.0.5 on 2021-03-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0002_auto_20210310_1146'),
        ('sapp', '0002_auto_20210310_1011'),
    ]

    operations = [
    ]
