# Generated by Django 3.0.5 on 2021-03-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_startup'),
        ('sapp', '0003_merge_20210312_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='int_investors',
            field=models.ManyToManyField(to='login.Investor'),
        ),
    ]
