# Generated by Django 3.0.5 on 2021-03-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0004_profile_int_investors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='int_investors',
        ),
    ]
